/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  isProgramError,
  type Address,
  type SOLANA_ERROR__INSTRUCTION_ERROR__CUSTOM,
  type SolanaError,
} from 'gill';
import { RAFFLE_VAULT_PROGRAM_ADDRESS } from '../programs';

/** InvalidTicketPrice: Ticket price must be greater than zero */
export const RAFFLE_VAULT_ERROR__INVALID_TICKET_PRICE = 0x1770; // 6000
/** InvalidDuration: Vault duration must be positive */
export const RAFFLE_VAULT_ERROR__INVALID_DURATION = 0x1771; // 6001
/** VaultClosed: Vault has already closed */
export const RAFFLE_VAULT_ERROR__VAULT_CLOSED = 0x1772; // 6002
/** VaultStillRunning: Vault is still running */
export const RAFFLE_VAULT_ERROR__VAULT_STILL_RUNNING = 0x1773; // 6003
/** MaxTicketsReached: Maximum number of tickets reached */
export const RAFFLE_VAULT_ERROR__MAX_TICKETS_REACHED = 0x1774; // 6004
/** TicketNotFound: Ticket not found for this payer */
export const RAFFLE_VAULT_ERROR__TICKET_NOT_FOUND = 0x1775; // 6005
/** NoTicketsSold: No tickets were sold */
export const RAFFLE_VAULT_ERROR__NO_TICKETS_SOLD = 0x1776; // 6006
/** RecipientMismatch: Recipient does not match winner */
export const RAFFLE_VAULT_ERROR__RECIPIENT_MISMATCH = 0x1777; // 6007
/** MathOverflow: Math overflow */
export const RAFFLE_VAULT_ERROR__MATH_OVERFLOW = 0x1778; // 6008
/** Unauthorized: Unauthorized */
export const RAFFLE_VAULT_ERROR__UNAUTHORIZED = 0x1779; // 6009
/** TicketsOutstanding: Tickets still outstanding */
export const RAFFLE_VAULT_ERROR__TICKETS_OUTSTANDING = 0x177a; // 6010
/** AlreadyEntered: Duplicate entry detected */
export const RAFFLE_VAULT_ERROR__ALREADY_ENTERED = 0x177b; // 6011
/** MissingBump: Missing bump seed in context */
export const RAFFLE_VAULT_ERROR__MISSING_BUMP = 0x177c; // 6012
/** PrizeAlreadyClaimed: Prize already claimed */
export const RAFFLE_VAULT_ERROR__PRIZE_ALREADY_CLAIMED = 0x177d; // 6013
/** WinnerAlreadyChosen: Winner already chosen */
export const RAFFLE_VAULT_ERROR__WINNER_ALREADY_CHOSEN = 0x177e; // 6014
/** NoPendingWinner: Missing pending winner */
export const RAFFLE_VAULT_ERROR__NO_PENDING_WINNER = 0x177f; // 6015
/** UnauthorizedClaim: Caller is not the recorded winner */
export const RAFFLE_VAULT_ERROR__UNAUTHORIZED_CLAIM = 0x1780; // 6016
/** NothingToPayout: Nothing to pay out */
export const RAFFLE_VAULT_ERROR__NOTHING_TO_PAYOUT = 0x1781; // 6017
/** UnauthorizedFinalize: Only the vault authority can finalize the payout */
export const RAFFLE_VAULT_ERROR__UNAUTHORIZED_FINALIZE = 0x1782; // 6018

export type RaffleVaultError =
  | typeof RAFFLE_VAULT_ERROR__ALREADY_ENTERED
  | typeof RAFFLE_VAULT_ERROR__INVALID_DURATION
  | typeof RAFFLE_VAULT_ERROR__INVALID_TICKET_PRICE
  | typeof RAFFLE_VAULT_ERROR__MATH_OVERFLOW
  | typeof RAFFLE_VAULT_ERROR__MAX_TICKETS_REACHED
  | typeof RAFFLE_VAULT_ERROR__MISSING_BUMP
  | typeof RAFFLE_VAULT_ERROR__NO_PENDING_WINNER
  | typeof RAFFLE_VAULT_ERROR__NOTHING_TO_PAYOUT
  | typeof RAFFLE_VAULT_ERROR__NO_TICKETS_SOLD
  | typeof RAFFLE_VAULT_ERROR__PRIZE_ALREADY_CLAIMED
  | typeof RAFFLE_VAULT_ERROR__RECIPIENT_MISMATCH
  | typeof RAFFLE_VAULT_ERROR__TICKET_NOT_FOUND
  | typeof RAFFLE_VAULT_ERROR__TICKETS_OUTSTANDING
  | typeof RAFFLE_VAULT_ERROR__UNAUTHORIZED
  | typeof RAFFLE_VAULT_ERROR__UNAUTHORIZED_CLAIM
  | typeof RAFFLE_VAULT_ERROR__UNAUTHORIZED_FINALIZE
  | typeof RAFFLE_VAULT_ERROR__VAULT_CLOSED
  | typeof RAFFLE_VAULT_ERROR__VAULT_STILL_RUNNING
  | typeof RAFFLE_VAULT_ERROR__WINNER_ALREADY_CHOSEN;

let raffleVaultErrorMessages: Record<RaffleVaultError, string> | undefined;
if (process.env.NODE_ENV !== 'production') {
  raffleVaultErrorMessages = {
    [RAFFLE_VAULT_ERROR__ALREADY_ENTERED]: `Duplicate entry detected`,
    [RAFFLE_VAULT_ERROR__INVALID_DURATION]: `Vault duration must be positive`,
    [RAFFLE_VAULT_ERROR__INVALID_TICKET_PRICE]: `Ticket price must be greater than zero`,
    [RAFFLE_VAULT_ERROR__MATH_OVERFLOW]: `Math overflow`,
    [RAFFLE_VAULT_ERROR__MAX_TICKETS_REACHED]: `Maximum number of tickets reached`,
    [RAFFLE_VAULT_ERROR__MISSING_BUMP]: `Missing bump seed in context`,
    [RAFFLE_VAULT_ERROR__NO_PENDING_WINNER]: `Missing pending winner`,
    [RAFFLE_VAULT_ERROR__NOTHING_TO_PAYOUT]: `Nothing to pay out`,
    [RAFFLE_VAULT_ERROR__NO_TICKETS_SOLD]: `No tickets were sold`,
    [RAFFLE_VAULT_ERROR__PRIZE_ALREADY_CLAIMED]: `Prize already claimed`,
    [RAFFLE_VAULT_ERROR__RECIPIENT_MISMATCH]: `Recipient does not match winner`,
    [RAFFLE_VAULT_ERROR__TICKET_NOT_FOUND]: `Ticket not found for this payer`,
    [RAFFLE_VAULT_ERROR__TICKETS_OUTSTANDING]: `Tickets still outstanding`,
    [RAFFLE_VAULT_ERROR__UNAUTHORIZED]: `Unauthorized`,
    [RAFFLE_VAULT_ERROR__UNAUTHORIZED_CLAIM]: `Caller is not the recorded winner`,
    [RAFFLE_VAULT_ERROR__UNAUTHORIZED_FINALIZE]: `Only the vault authority can finalize the payout`,
    [RAFFLE_VAULT_ERROR__VAULT_CLOSED]: `Vault has already closed`,
    [RAFFLE_VAULT_ERROR__VAULT_STILL_RUNNING]: `Vault is still running`,
    [RAFFLE_VAULT_ERROR__WINNER_ALREADY_CHOSEN]: `Winner already chosen`,
  };
}

export function getRaffleVaultErrorMessage(code: RaffleVaultError): string {
  if (process.env.NODE_ENV !== 'production') {
    return (raffleVaultErrorMessages as Record<RaffleVaultError, string>)[code];
  }

  return 'Error message not available in production bundles.';
}

export function isRaffleVaultError<TProgramErrorCode extends RaffleVaultError>(
  error: unknown,
  transactionMessage: {
    instructions: Record<number, { programAddress: Address }>;
  },
  code?: TProgramErrorCode
): error is SolanaError<typeof SOLANA_ERROR__INSTRUCTION_ERROR__CUSTOM> &
  Readonly<{ context: Readonly<{ code: TProgramErrorCode }> }> {
  return isProgramError<TProgramErrorCode>(
    error,
    transactionMessage,
    RAFFLE_VAULT_PROGRAM_ADDRESS,
    code
  );
}
