/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  containsBytes,
  fixEncoderSize,
  getBytesEncoder,
  type Address,
  type ReadonlyUint8Array,
} from 'gill';
import {
  type ParsedCancelRaffleInstruction,
  type ParsedClaimRaffleInstruction,
  type ParsedEnterRaffleInstruction,
  type ParsedExitRaffleInstruction,
  type ParsedInitializeRaffleInstruction,
  type ParsedPayoutRaffleInstruction,
} from '../instructions';

export const RAFFLE_VAULT_PROGRAM_ADDRESS =
  'BRWhr8mqPoi9gsKrie32hWdLU2jWKBh3PixLXg4sAytA' as Address<'BRWhr8mqPoi9gsKrie32hWdLU2jWKBh3PixLXg4sAytA'>;

export enum RaffleVaultAccount {
  Vault,
}

export function identifyRaffleVaultAccount(
  account: { data: ReadonlyUint8Array } | ReadonlyUint8Array
): RaffleVaultAccount {
  const data = 'data' in account ? account.data : account;
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([211, 8, 232, 43, 2, 152, 117, 119])
      ),
      0
    )
  ) {
    return RaffleVaultAccount.Vault;
  }
  throw new Error(
    'The provided account could not be identified as a raffleVault account.'
  );
}

export enum RaffleVaultInstruction {
  CancelRaffle,
  ClaimRaffle,
  EnterRaffle,
  ExitRaffle,
  InitializeRaffle,
  PayoutRaffle,
}

export function identifyRaffleVaultInstruction(
  instruction: { data: ReadonlyUint8Array } | ReadonlyUint8Array
): RaffleVaultInstruction {
  const data = 'data' in instruction ? instruction.data : instruction;
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([135, 191, 223, 141, 192, 186, 234, 254])
      ),
      0
    )
  ) {
    return RaffleVaultInstruction.CancelRaffle;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([193, 113, 8, 101, 7, 208, 64, 116])
      ),
      0
    )
  ) {
    return RaffleVaultInstruction.ClaimRaffle;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([153, 168, 28, 44, 235, 94, 238, 243])
      ),
      0
    )
  ) {
    return RaffleVaultInstruction.EnterRaffle;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([9, 51, 59, 168, 240, 75, 231, 83])
      ),
      0
    )
  ) {
    return RaffleVaultInstruction.ExitRaffle;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([110, 142, 92, 16, 15, 58, 89, 229])
      ),
      0
    )
  ) {
    return RaffleVaultInstruction.InitializeRaffle;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([167, 137, 113, 225, 81, 253, 87, 9])
      ),
      0
    )
  ) {
    return RaffleVaultInstruction.PayoutRaffle;
  }
  throw new Error(
    'The provided instruction could not be identified as a raffleVault instruction.'
  );
}

export type ParsedRaffleVaultInstruction<
  TProgram extends string = 'BRWhr8mqPoi9gsKrie32hWdLU2jWKBh3PixLXg4sAytA',
> =
  | ({
      instructionType: RaffleVaultInstruction.CancelRaffle;
    } & ParsedCancelRaffleInstruction<TProgram>)
  | ({
      instructionType: RaffleVaultInstruction.ClaimRaffle;
    } & ParsedClaimRaffleInstruction<TProgram>)
  | ({
      instructionType: RaffleVaultInstruction.EnterRaffle;
    } & ParsedEnterRaffleInstruction<TProgram>)
  | ({
      instructionType: RaffleVaultInstruction.ExitRaffle;
    } & ParsedExitRaffleInstruction<TProgram>)
  | ({
      instructionType: RaffleVaultInstruction.InitializeRaffle;
    } & ParsedInitializeRaffleInstruction<TProgram>)
  | ({
      instructionType: RaffleVaultInstruction.PayoutRaffle;
    } & ParsedPayoutRaffleInstruction<TProgram>);
